name: Dillon Buchanan
markdown: redcarpet
pygments: true
paginate: 5
permalink: /:categories/:title/
paginate_path: "page/:num"
excerpt_separator: "\n"

web_url: "http://www.dillonbuchanan.com"

# Stuff for the website
description: "Hello there! I'm Dillon Buchanan, a software developer and all-around programming enthusist working in Boston. I love creating great software!"
blog_logo: "https://avatars2.githubusercontent.com/u/1644068?s=460"

gems:
  - jekyll-sitemap
